### ISSUE TITLE
[Bug]: 429 You exceeded your current quota

### ISSUE THREAD

**Issue by bashijiu2020** [Kuingsmile/word-GPT-Plus#80]
### 前置阅读 | Pre-reading

- [X] [Issues](https://github.com/Kuingsmile/word-gpt-plus/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [README](https://github.com/Kuingsmile/word-gpt-plus/blob/master/README.md)

### 服务类型 | Service Type

Official hosted service

### 系统信息 | System Information

Windows

### Office 版本 | Office Version

office 2021

### 问题重现 | Bug reproduce

429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I've updated the error handling in the official API integration to specifically catch and handle the 429 (quota exceeded) error. This will provide a more informative message to the user when they've exceeded their API quota.

I also created pull request: https://github.com/Kuingsmile/word-GPT-Plus/pull/81


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by Kuingsmile** [comment]
Check your billing

**Comment by bashijiu2020** [comment]
我是Chatgpt plus 用户，网页是可以登陆的，但是在这个插件里导入API KEY,无论4o还是3.5，都是不行的。
4o: 404 The model `gpt-4o` does not exist or you do not have access to it.
3.5: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
palm: AxiosError: Request failed with status code 400

**Comment by Kuingsmile** [comment]
和plus或网页版无关 是openai api的权限与付费
